In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Student_Grades.csv')

In [3]:
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [4]:
df.shape

(571, 43)

In [5]:
df.columns

Index(['Seat No.', 'PH-121', 'HS-101', 'CY-105', 'HS-105/12', 'MT-111',
       'CS-105', 'CS-106', 'EL-102', 'EE-119', 'ME-107', 'CS-107', 'HS-205/20',
       'MT-222', 'EE-222', 'MT-224', 'CS-210', 'CS-211', 'CS-203', 'CS-214',
       'EE-217', 'CS-212', 'CS-215', 'MT-331', 'EF-303', 'HS-304', 'CS-301',
       'CS-302', 'TC-383', 'MT-442', 'EL-332', 'CS-318', 'CS-306', 'CS-312',
       'CS-317', 'CS-403', 'CS-421', 'CS-406', 'CS-414', 'CS-419', 'CS-423',
       'CS-412', 'CGPA'],
      dtype='object')

In [6]:
col_null=df.columns[df.isnull().any()].tolist()

In [7]:
df[col_null]

,CY-105,HS-105/12,MT-111,CS-106,EL-102,EE-119,ME-107,CS-107,HS-205/20,MT-222,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,C-,C,C-,D,C-,B-,C-,C-,B+,D,...,C,C-,C-,C-,C-,A-,A,C-,B,A-
1,D+,D,B-,D,A,D+,D,B+,C+,B-,...,D,D+,D,C,D,A-,B-,C,C,B
2,A,B-,B+,B-,B+,A-,A-,B-,A-,A,...,A-,B,B,A,C,A,A,A,A-,A
3,D+,D,D,D+,C-,D,C+,D,B,D+,...,C-,D+,C,D+,C-,B-,B,C+,C+,C+
4,A-,B+,A,A-,B+,A,A-,C,A,A,...,A-,B-,B+,B+,B-,A-,A,A-,A-,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,A,A-,A+,A-,A-,A+,B+,A+,A,A+,...,B+,A-,A-,A,A,A,B+,B+,B,A
567,A,A,A,A,A-,A,A,A+,B+,C+,...,A-,B+,B+,A,A,A-,B,A-,C,A-
568,A-,B+,A,A,A,A,B,A+,B-,B,...,B+,A-,B,A,B+,A,C,B+,A-,A-
569,D,A,D,B-,C-,B-,C-,A+,C+,D,...,B+,D,B,B,C-,D,C,B,B-,C
570,D,C,C,B,C+,C,D+,B-,C+,C-,...,D+,C+,C,B-,D,F,C-,B+,D,C-

In [8]:
df[col_null]

,CY-105,HS-105/12,MT-111,CS-106,EL-102,EE-119,ME-107,CS-107,HS-205/20,MT-222,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,C-,C,C-,D,C-,B-,C-,C-,B+,D,...,C,C-,C-,C-,C-,A-,A,C-,B,A-
1,D+,D,B-,D,A,D+,D,B+,C+,B-,...,D,D+,D,C,D,A-,B-,C,C,B
2,A,B-,B+,B-,B+,A-,A-,B-,A-,A,...,A-,B,B,A,C,A,A,A,A-,A
3,D+,D,D,D+,C-,D,C+,D,B,D+,...,C-,D+,C,D+,C-,B-,B,C+,C+,C+
4,A-,B+,A,A-,B+,A,A-,C,A,A,...,A-,B-,B+,B+,B-,A-,A,A-,A-,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,A,A-,A+,A-,A-,A+,B+,A+,A,A+,...,B+,A-,A-,A,A,A,B+,B+,B,A
567,A,A,A,A,A-,A,A,A+,B+,C+,...,A-,B+,B+,A,A,A-,B,A-,C,A-
568,A-,B+,A,A,A,A,B,A+,B-,B,...,B+,A-,B,A,B+,A,C,B+,A-,A-
569,D,A,D,B-,C-,B-,C-,A+,C+,D,...,B+,D,B,B,C-,D,C,B,B-,C
570,D,C,C,B,C+,C,D+,B-,C+,C-,...,D+,C+,C,B-,D,F,C-,B+,D,C-

In [9]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy="most_frequent")
df[col_null]=pd.DataFrame(si.fit_transform(df[col_null]),columns=df[col_null].columns)

In [10]:
df.isnull().sum().sum()

0

In [11]:
for i in col_null:
    print(i,df[i].unique())

CY-105 ['C-' 'D+' 'A' 'A-' 'B' 'C+' 'B+' 'B-' 'C' 'D' 'WU' 'A+' 'F']
HS-105/12 ['C' 'D' 'B-' 'B+' 'D+' 'B' 'C-' 'C+' 'A-' 'A' 'WU' 'A+' 'F']
MT-111 ['C-' 'B-' 'B+' 'D' 'A' 'C+' 'A-' 'C' 'B' 'D+' 'A+' 'F' 'WU']
CS-106 ['D' 'B-' 'D+' 'A-' 'C+' 'A' 'C-' 'C' 'B' 'B+' 'A+' 'F' 'WU']
EL-102 ['C-' 'A' 'B+' 'B' 'A-' 'B-' 'C' 'C+' 'D+' 'D' 'A+' 'WU' 'F']
EE-119 ['B-' 'D+' 'A-' 'D' 'A' 'B+' 'B' 'C-' 'C+' 'C' 'WU' 'A+']
ME-107 ['C-' 'D' 'A-' 'C+' 'B+' 'A' 'D+' 'C' 'B' 'B-' 'WU' 'F' 'A+']
CS-107 ['C-' 'B+' 'B-' 'D' 'C' 'A-' 'C+' 'D+' 'B' 'A' 'A+' 'I' 'WU' 'F']
HS-205/20 ['B+' 'C+' 'A-' 'B' 'A' 'B-' 'D' 'WU' 'A+' 'C' 'D+' 'C-' 'F']
MT-222 ['D' 'B-' 'A' 'D+' 'C' 'B+' 'A-' 'B' 'C+' 'C-' 'WU' 'F' 'A+' 'W']
EE-222 ['A-' 'C-' 'A' 'B-' 'B+' 'C+' 'D+' 'B' 'C' 'W' 'A+' 'D' 'F']
MT-224 ['B-' 'D+' 'A' 'D' 'A-' 'C-' 'C' 'B+' 'C+' 'B' 'A+' 'WU' 'W' 'F']
CS-210 ['C+' 'D+' 'A' 'C' 'A-' 'B+' 'B-' 'B' 'D' 'A+' 'C-' 'WU' 'W' 'F']
CS-211 ['D+' 'D' 'A+' 'B+' 'B-' 'B' 'A-' 'C-' 'C+' 'C' 'A' 'WU' 'F' 'W']
CS-203 ['D+' 'C' 'A' 'C+' 'A-' 'B+' 'B' 'B-' 'C-' 'D' 'A+' 'I' 'F']
CS-214 ['D' 'A-' 'B' 'C' 'B-' 'C+' 'A' 'C-' 'B+' 'D+' 'I' 'F' 'A+']
EE-217 ['A' 'B-' 'D+' 'A-' 'A+' 'C' 'B+' 'B' 'C-' 'D' 'WU' 'F' 'C+']
CS-212 ['D' 'C' 'A-' 'C+' 'B-' 'D+' 'B+' 'B' 'A' 'C-' 'A+' 'WU']
CS-215 ['C-' 'D' 'A' 'A-' 'C+' 'C' 'B+' 'B-' 'D+' 'B' 'A+' 'WU' 'W' 'F']
MT-331 ['C' 'D+' 'A' 'C+' 'B+' 'A-' 'B' 'B-' 'A+' 'D' 'C-' 'F']
EF-303 ['C-' 'D' 'C+' 'B+' 'C' 'D+' 'A-' 'B-' 'A' 'B' 'WU' 'F']
HS-304 ['C+' 'C-' 'A' 'B-' 'A-' 'B+' 'B' 'C' 'D' 'D+' 'A+' 'WU' 'F' 'W']
CS-301 ['B' 'A-' 'B+' 'D' 'B-' 'D+' 'C' 'C+' 'C-' 'A' 'F' 'A+']
CS-302 ['C' 'D+' 'A-' 'B-' 'C+' 'B' 'D' 'B+' 'A' 'C-' 'A+']
TC-383 ['C+' 'C-' 'B' 'D+' 'C' 'B+' 'B-' 'D' 'A-' 'A' 'F' 'A+']
MT-442 ['B+' 'C-' 'A' 'A-' 'B' 'A+' 'C+' 'B-' 'C' 'D+' 'D' 'F']
EL-332 ['C' 'B+' 'D+' 'A-' 'B' 'A' 'B-' 'C-' 'C+' 'D' 'A+' 'F' 'WU']
CS-318 ['C-' 'A-' 'B+' 'B-' 'C' 'B' 'C+' 'D' 'D+' 'A' 'A+' 'WU' 'F' 'W']
CS-306 ['C' 'D' 'A-' 'C-' 'B+' 'C+' 'B-' 'B' 'A' 'D+' 'A+' 'F' 'WU']
CS-312 ['C-' 'D+' 'B' 'B-' 'C' 'B+' 'C+' 'A-' 'D' 'A+' 'A' 'F' 'W' 'WU']
CS-317 ['C-' 'D' 'B' 'C' 'B+' 'B-' 'A-' 'D+' 'C+' 'A' 'A+' 'F']
CS-403 ['C-' 'C' 'A' 'D+' 'B+' 'C+' 'B-' 'A-' 'B' 'A+' 'D']
CS-421 ['C-' 'D' 'C' 'B-' 'C+' 'B+' 'D+' 'B' 'A' 'A-' 'F' 'A+' 'W']
CS-406 ['A-' 'A' 'B-' 'B' 'B+' 'C+' 'D' 'D+' 'C-' 'C' 'A+' 'F' 'W' 'WU']
CS-414 ['A' 'B-' 'B' 'A-' 'B+' 'A+' 'C' 'C-' 'C+' 'F' 'D+' 'W' 'D']
CS-419 ['C-' 'C' 'A' 'C+' 'A-' 'B+' 'B-' 'B' 'D+' 'A+' 'D' 'F']
CS-423 ['B' 'C' 'A-' 'C+' 'B-' 'B+' 'C-' 'A' 'D+' 'D' 'A+' 'F']
CS-412 ['A-' 'B' 'A' 'C+' 'B+' 'C-' 'B-' 'A+' 'C' 'D+' 'F' 'W' 'D']

In [12]:
df.drop('Seat No.',axis=1,inplace=True)

In [13]:
df

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,B-,D+,C-,C,C-,D+,D,C-,B-,C-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,A,D,D+,D,B-,C,D,A,D+,D,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,A,B,A,B-,B+,A,B-,B+,A-,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,D,C+,D+,D,D,A-,D+,C-,D,C+,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,A-,A-,A-,B+,A,A,A-,B+,A,A-,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,B,A,A,A-,A+,A,A-,A-,A+,B+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,A+,A,A,A,A,A,A,A-,A,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,B,A,A-,B+,A,A,A,A,A,B,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,A,B+,D,A,D,D+,B-,C-,B-,C-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,C,D,D,C,C,D+,B,C+,C,D+,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
    if df[i].dtypes=='object':
        df[i]=le.fit_transform(df[i])

In [15]:
df

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,5,10,8,6,8,10,9,8,5,8,...,8,8,8,8,2,0,8,3,2,2.205
1,0,9,10,9,5,6,9,0,10,9,...,10,9,6,9,2,5,6,6,3,2.008
2,0,3,0,5,4,0,5,4,2,2,...,3,3,0,6,0,0,0,2,0,3.608
3,9,7,10,9,9,2,10,8,9,7,...,10,6,10,8,5,3,7,7,7,1.906
4,2,2,2,4,0,0,2,4,0,2,...,5,4,4,5,2,0,2,2,0,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,3,0,0,2,1,0,2,2,1,4,...,2,2,0,0,0,4,4,3,0,3.798
567,1,0,0,0,0,0,0,2,0,0,...,4,4,0,0,2,3,2,6,2,3.772
568,3,0,2,4,0,0,0,0,0,3,...,2,3,0,4,0,6,4,2,2,3.470
569,0,4,9,0,9,10,5,8,5,8,...,9,3,3,8,9,6,3,5,6,2.193
570,6,9,9,6,6,10,3,7,6,10,...,7,6,5,9,11,8,4,9,8,1.753

In [16]:
x=df.drop('CGPA',axis=1)

In [17]:
x

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,5,10,8,6,8,10,9,8,5,8,...,6,8,8,8,8,2,0,8,3,2
1,0,9,10,9,5,6,9,0,10,9,...,9,10,9,6,9,2,5,6,6,3
2,0,3,0,5,4,0,5,4,2,2,...,2,3,3,0,6,0,0,0,2,0
3,9,7,10,9,9,2,10,8,9,7,...,8,10,6,10,8,5,3,7,7,7
4,2,2,2,4,0,0,2,4,0,2,...,2,5,4,4,5,2,0,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,3,0,0,2,1,0,2,2,1,4,...,4,2,2,0,0,0,4,4,3,0
567,1,0,0,0,0,0,0,2,0,0,...,2,4,4,0,0,2,3,2,6,2
568,3,0,2,4,0,0,0,0,0,3,...,4,2,3,0,4,0,6,4,2,2
569,0,4,9,0,9,10,5,8,5,8,...,4,9,3,3,8,9,6,3,5,6
570,6,9,9,6,6,10,3,7,6,10,...,10,7,6,5,9,11,8,4,9,8

In [18]:
y=df['CGPA']

In [19]:
y

0      2.205
1      2.008
2      3.608
3      1.906
4      3.448
       ...
566    3.798
567    3.772
568    3.470
569    2.193
570    1.753
Name: CGPA, Length: 571, dtype: float64

In [20]:
x.value_counts()

PH-121  HS-101  CY-105  HS-105/12  MT-111  CS-105  CS-106  EL-102  EE-119  ME-107  CS-107  HS-205/20  MT-222  EE-222  MT-224  CS-210  CS-211  CS-203  CS-214  EE-217  CS-212  CS-215  MT-331  EF-303  HS-304  CS-301  CS-302  TC-383  MT-442  EL-332  CS-318  CS-306  CS-312  CS-317  CS-403  CS-421  CS-406  CS-414  CS-419  CS-423  CS-412
0       0       0       0          7       0       4       6       4       4       7       4          0       5       4       2       5       7       7       6       2       3       4       1       5       2       0       4       2       5       6       3       3       3       3       3       5       2       0       7       3         1
5       5       2       0          3       0       3       4       2       4       5       3          0       3       5       4       3       3       8       4       3       3       0       3       2       3       4       4       0       3       6       3       0       5       0       3       3       4       4       5       3         1
        3       6       2          8       0       2       5       3       9       2       5          4       2       6       8       10      8       4       3       10      6       6       9       2       8       5       6       4       6       3       5       8       6       2       6       2       2       5       4       2         1
        4       0       0          0       0       4       1       2       2       0       2          4       0       0       0       1       0       0       0       2       0       0       2       0       0       0       0       0       1       4       1       1       2       3       4       2       0       4       0       2         1
                        4          2       5       3       0       3       5       4       0          6       3       2       2       2       3       2       0       3       3       0       2       3       0       0       2       2       0       4       2       1       2       2       3       2       0       4       0       4         1
                                                                                                                                                                                                                                                                                                                                               ..
2       5       0       7          5       2       7       3       2       5       7       0          2       4       5       2       7       2       5       2       5       5       3       4       2       2       2       6       0       2       2       3       6       2       2       2       0       1       3       0       0         1
                        4          0       0       3       0       0       5       2       0          0       0       2       0       0       0       0       1       0       0       0       1       4       0       0       2       0       0       0       0       2       2       2       7       2       0       2       0       2         1
                        2          2       0       2       5       3       4       3       3          3       4       5       2       4       2       3       4       2       0       3       3       3       2       4       2       2       4       5       3       2       7       0       0       4       5       2       7       3         1
                        0          2       0       4       2       4       0       5       3          7       4       5       2       2       4       5       2       3       2       0       3       7       4       4       3       2       7       3       5       4       4       0       3       6       9       2       10      6         1
12      10      11      11         11      9       2       9       11      11      9       11         11      12      12      12      11      11      11      11      11      12      0       2       2       2       2       0       2       2       2       2       1       5       0       3       2       0       2       2       2         1
Length: 571, dtype: int64

In [21]:
y.value_counts()

3.019    5
3.058    3
2.793    3
3.443    3
2.206    3
        ..
2.555    1
2.042    1
2.634    1
2.053    1
1.753    1
Name: CGPA, Length: 491, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression

In [23]:
MaxAcc=0
MaxRS=0
for i in range(0,200):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=i)
    lr=LinearRegression()
    lr.fit(x_train,y_train)
    pred=lr.predict(x_test,)
    acc=r2_score(y_test,pred)
    if acc>MaxAcc:
        MaxAcc=acc
        MaxRS=i
print("Maximum R2 Score=",MaxAcc,"Maximum Random State=",MaxRS)

Maximum R2 Score= 0.9643494726169242 Maximum Random State= 72

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=MaxRS)

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Lasso,Ridge
from sklearn.svm import SVR

In [30]:
lr=LinearRegression()
lr.fit(x_train,y_train)
predLR=lr.predict(x_test)
predLR_train=lr.predict(x_train)
print("r2 score:",r2_score(y_test,predLR))
print("r2 score on train data:",r2_score(y_train,predLR_train))
print("Mean Absolute Error:",mean_absolute_error(y_test,predLR))
print("Mean_square_error",mean_squared_error(y_test,predLR))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predLR)))

r2 score: 0.9643494726169242
r2 score on train data: 0.9139022616556756
Mean Absolute Error: 0.0893834077440855
Mean_square_error 0.013741931476875207
RMSE: 0.1172259846487766

In [32]:
GBR=GradientBoostingRegressor()
GBR.fit(x_train,y_train)
predGBR=GBR.predict(x_test)
predGBR_train=GBR.predict(x_train)
print("R2 Score:",r2_score(y_test,predGBR))
print("R2 score on train data=",r2_score(y_train,predGBR_train))
print("Mean Absolute Error:",mean_absolute_error(y_test,predGBR))
print("Mean Squared Error:",mean_squared_error(y_test,predGBR))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predGBR)))

R2 Score: 0.9670248292429691
R2 score on train data= 0.9953002375042729
Mean Absolute Error: 0.08273671984182417
Mean Squared Error: 0.012710682568934366
RMSE: 0.1127416629686398

In [33]:
DTR=DecisionTreeRegressor()
DTR.fit(x_train,y_train)
predDTR=DTR.predict(x_test)
predDTR_train=DTR.predict(x_train)
print("R2 Score:",r2_score(y_test,predDTR))
print("R2 score on train data=",r2_score(y_train,predDTR_train))
print("Mean Absolute Error:",mean_absolute_error(y_test,predDTR))
print("Mean Squared Error:",mean_squared_error(y_test,predDTR))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predDTR)))

R2 Score: 0.8217639102694178
R2 score on train data= 1.0
Mean Absolute Error: 0.19030232558139532
Mean Squared Error: 0.06870327906976742
RMSE: 0.2621131035827233

In [34]:
LA=Lasso()
LA.fit(x_train,y_train)
predLA=LA.predict(x_test)
predLA_train=LA.predict(x_train)
print("R2 Score:",r2_score(y_test,predLA))
print("R2 score on train data=",r2_score(y_train,predLA_train))
print("Mean Absolute Error:",mean_absolute_error(y_test,predLA))
print("Mean Squared Error:",mean_squared_error(y_test,predLA))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predLA)))

R2 Score: 0.350609991970284
R2 score on train data= 0.33484914041131697
Mean Absolute Error: 0.4242155056363917
Mean Squared Error: 0.2503153150084445
RMSE: 0.50031521564754

In [36]:
RD=Ridge()
RD.fit(x_train,y_train)
predRD=RD.predict(x_test)
predRD_train=RD.predict(x_train)
print("r2 Score:",r2_score(y_test,predRD))
print("r2 score on train data:",r2_score(y_train,predRD_train))
print("MAE:",mean_absolute_error(y_test,predRD))
print("MSE:",mean_squared_error(y_test,predRD))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predRD)))

r2 Score: 0.9643771003828862
r2 score on train data: 0.9139022436130492
MAE: 0.08935085255469426
MSE: 0.013731282016836948
RMSE: 0.11718055306592877

In [37]:
knn=KNN()
knn.fit(x_train,y_train)
predknn=knn.predict(x_test)
predknn_train=knn.predict(x_train)
print("R2 Score:",r2_score(y_test,predknn))
print("R2 score on train data=",r2_score(y_train,predknn_train))
print("Mean Absolute Error:",mean_absolute_error(y_test,predknn))
print("Mean Squared Error:",mean_squared_error(y_test,predknn))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predknn)))

R2 Score: 0.9678399340351564
R2 score on train data= 0.9142712169240712
Mean Absolute Error: 0.08414302325581392
Mean Squared Error: 0.012396490465116273
RMSE: 0.11133952786461901

In [38]:
svr=SVR()
svr.fit(x_train,y_train)
predsvr=svr.predict(x_test)
predsvr_train=svr.predict(x_train)
print("R2 Score:",r2_score(y_test,predsvr))
print("R2 score on train data=",r2_score(y_train,predsvr_train))
print("Mean Absolute Error:",mean_absolute_error(y_test,predsvr))
print("Mean Squared Error:",mean_squared_error(y_test,predsvr))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predsvr)))

R2 Score: 0.9729068281692774
R2 score on train data= 0.9581722934535725
Mean Absolute Error: 0.07778518158705636
Mean Squared Error: 0.010443394196904394
RMSE: 0.10219292635453979

In [42]:
from sklearn.model_selection import cross_val_score

In [48]:
scorelr=cross_val_score(lr,x,y,cv=5)
print(scorelr)
print(scorelr.mean())
print("Difference between r2 Score and cross val score:",r2_score(y_test,predLR)-(scorelr.mean()))

[0.8927601  0.93427094 0.90082619 0.94061762 0.84878197]
0.9034513625626616
Difference between r2 Score and cross val score: 0.0608981100542626

In [50]:
scoreGBR=cross_val_score(GBR,x,y,cv=5)
print(scoreGBR)
print(scoreGBR.mean())
print("Difference Between r2 score and cross val score",r2_score(y_test,predGBR)-(scoreGBR.mean()))

[0.9200457  0.95816997 0.95345422 0.94561604 0.87508685]
0.9304745573251653
Difference Between r2 score and cross val score 0.0365502719178038

In [51]:
scoreDTR=cross_val_score(DTR,x,y,cv=5)
print(scoreDTR)
print(scoreDTR.mean())
print("Difference Between r2 score and cross val score",r2_score(y_test,predDTR)-(scoreDTR.mean()))

[0.75534093 0.80893496 0.87055083 0.73810666 0.75281352]
0.7851493809865678
Difference Between r2 score and cross val score 0.03661452928284992

In [52]:
scoreLA=cross_val_score(LA,x,y,cv=5)
print(scoreLA)
print(scoreLA.mean())
print("Difference Between r2 score and cross val score",r2_score(y_test,predLA)-(scoreLA.mean()))

[0.34542541 0.3341994  0.3340023  0.37377257 0.28984562]
0.33544905937176195
Difference Between r2 score and cross val score 0.015160932598522026

In [53]:
scoreRD=cross_val_score(RD,x,y,cv=5)
print(scoreRD)
print(scoreRD.mean())
print("Difference Between r2 score and cross val score",r2_score(y_test,predRD)-(scoreRD.mean()))

[0.89277522 0.93427636 0.90085156 0.94066429 0.84879596]
0.9034726777742446
Difference Between r2 score and cross val score 0.060904422608641595

In [54]:
scoresvr=cross_val_score(svr,x,y,cv=5)
print(scoresvr)
print(scoresvr.mean())
print("Difference Between r2 score and cross val score",r2_score(y_test,predsvr)-(scoresvr.mean()))

[0.89588569 0.92619817 0.91481769 0.94868905 0.85529357]
0.9081768357886064
Difference Between r2 score and cross val score 0.06472999238067101

In [55]:
scoreknn=cross_val_score(knn,x,y,cv=5)
print(scoreknn)
print(scoreknn.mean())
print("Difference Between r2 score and cross val score",r2_score(y_test,predknn)-(scoreknn.mean()))

[0.88704165 0.93105804 0.86498494 0.95195617 0.81245731]
0.8894996210901137
Difference Between r2 score and cross val score 0.07834031294504273

GBR is our best fit model because it has high accuracy and lowest difference between r2score and cross val score

Hyper parameter tuning

In [56]:
from sklearn.model_selection import GridSearchCV

In [77]:
parameters={'learning_rate':[.1,0.01,0.001],
           'n_estimators':[1,5,10,23],
           'min_samples_split':[3,9,10,12],
            'max_depth':[3],
           'random_state':[2,7,10,14]}

In [78]:
gscv=GridSearchCV(GBR,parameters,cv=5)
gscv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(),
             param_grid={'learning_rate': [0.1, 0.01, 0.001], 'max_depth': [3],
                         'min_samples_split': [3, 9, 10, 12],
                         'n_estimators': [1, 5, 10, 23],
                         'random_state': [2, 7, 10, 14]})

In [79]:
gscv.best_params_

{'learning_rate': 0.1,
 'max_depth': 3,
 'min_samples_split': 3,
 'n_estimators': 23,
 'random_state': 7}

In [80]:
Model=GradientBoostingRegressor(learning_rate=.1,max_depth=3,min_samples_split=3,n_estimators=23,random_state=7)

In [82]:
Model.fit(x_train,y_train)
predM=Model.predict(x_test)
print("R2 score:",r2_score(y_test,predM))
print("MAE:",mean_absolute_error(y_test,predM))
print("MSE:",mean_squared_error(y_test,predM))
print("RMSE:",np.sqrt(mean_squared_error(y_test,predM)))

R2 score: 0.9215362465118973
MAE: 0.1383620283228541
MSE: 0.030244812713873217
RMSE: 0.17391035827078621

In [83]:
import joblib

In [85]:
joblib.dump(Model,'Students_grades.pkl')

['Students_grades.pkl']

In [86]:
loaded_model=joblib.load('Students_grades.pkl')
y_pred=loaded_model.predict(x_test)
test_score=r2_score(y_test,y_pred)
print("Test R2 Score:",test_score*100)

Test R2 Score: 92.15362465118973

In [87]:
conclusion=pd.DataFrame([loaded_model.predict(x_test)[:],y_test[:]],index=["Predicted","Original"])
conclusion

,0,1,2,3,4,5,6,7,8,9,...,162,163,164,165,166,167,168,169,170,171
Predicted,2.192161,3.476505,3.190179,2.710532,2.840179,3.596778,3.236455,3.715019,3.290465,3.715019,...,2.567772,2.646735,2.910832,2.806967,2.277206,2.207491,3.507931,2.880684,2.2656,3.520692
Original,2.288000,3.566000,3.114000,2.384000,2.311000,3.700000,3.350000,3.943000,3.443000,3.908000,...,2.564000,2.484000,2.917000,2.782000,2.321000,2.188000,3.554000,3.058000,2.0870,3.647000